vaadin/vaadin-button

- gulpfile.js
Related to https://github.com/vaadin/vaadin-element-skeleton/pull/29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/15)
> Include subfolders of `demo` and `test` folders for linting

- bower.json
- docs.json
- index.html
- vaadin-button.html
Connects to https://github.com/vaadin/components-team-tasks/issues/239
Depends on https://github.com/vaadin/vaadin-text-field/pull/61 being merged first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/13)
> Replace iron-component-page with api-doc-viewer

- vaadin-button.html
Not sure if this should be here, maybe `vaadin-themes` repo could provide a special theme with styles grabbed from `normalize.css`? If so, close this PR and I'll send another one to implement it there. But placing such styles together with element itself looks more clear for end-users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/29)
> Add styles for native button from normalize.css. Closes #28

- vaadin-button.html
`:-moz-focusring` only supported in older Firefox (4.x), so `:-moz-focusring` rule not needed either. Remove `text-transform: none`. Fixes #28
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/31)
> Revert Mozilla specific styles

- vaadin-button.html
Create the `vaadin-button-default-theme` to avoid the following warning:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/37)
> Create the vaadin-button-default-theme

- vaadin-button.html
Fixes #46 
Add back the import of Polymer.GestureEventListeners as it required for `down` and `up` event listeners for changing `active` state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/50)
> Polymer.GestureEventListeners

- theme/valo/vaadin-button.html
The line height of the parent scope is the one that sets the vertical alignment context, so in order to play nice with other content, we should not adjust it for the button host element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/59)
> Fix host vertical align

- bower.json
- demo/index.html
- test/visual/valo.html
- theme/valo/vaadin-button.html
This property will be added in the next Valo theme version. For now, the icon size will default to 24px (iron-icon default).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/60)
> Use the `--valo-icon-size` property

- theme/valo/vaadin-button.html
Fix active style for macOS “tap-to-click” by reducing the transition duration to 0 for the active state.
Adjust primary button hover and active styles to be slightly more prominent and consistent with the other button types.
Adjust the tertiary type activation style to use opacity instead of color.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/62)
> Adjust hover and active state styles

- src/vaadin-button.html
- test/vaadin-button_test.html
Connected to vaadin/vaadin-date-picker#505
Note: there was a similar issue with `vaadin-item` fixed previously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/65)
> Remove active state when disconnected from the DOM

- demo/button-basic-demos.html
- src/vaadin-button.html
- theme/lumo/vaadin-button.html
Fixes #66 
The issue related to the HTML minification was caused by the IE-specific workaround, introduced because of the `min-height` flex bug (yes, this rabbit hole goes really deep).
So after some discussion with @jouni we decided to break this ugly chain of hacks and workarounds by just using fixed height.
Since this is a breaking change anyways, we are inclined to remove the `!important` on the host element at the same time, getting rid of that evil stuff as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/69)
> Remove IE11 workaround, update theme to use height

- .travis.yml
- test/index.html
- test/vaadin-button_test.html
- wct.conf.js
Connected to vaadin/components-team-tasks#332
Also did some cleanup to eliminate the single legacy `Polymer.dom` usage.
The `mock-interactions` change is needed because of the fact that `mock-interactions.js` still use the `Polymer.Base.async` and the HTML file imports the needed dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/82)
> Use bare module specifiers in the P3 conversion

- theme/lumo/vaadin-button.html
The potential benefit of the modularized style modules is currently less valuable than the potential performance benefit of combining them.
I have not measured the performance impact – this is based on my understanding how the style modules are processed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/85)
> Combine style modules

- demo/button-theme-variants-demos.html
- demo/demos.json
Connects to "Guidelines for component examples": "Avoid using product specific names or words that do not describe the contents of the category"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/92)
> Rename Lumo Theme demo to Theme Variants

- demo/button-basic-demos.html
The file had two `<vaadin-demo-snippet id='button-basic-demos-disabled'>` with the same `id` under different headers ("Disabled" and "Using an Icon")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/105)
> Fix duplicate id attribute in demo

- theme/lumo/vaadin-button-styles.html
See https://github.com/vaadin/vaadin-button/issues/79#issuecomment-377670959.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/80)
> Set visible overflow for tertiary-inline label

- src/vaadin-button.html
- test/vaadin-button_test.html
Fixes #124 
Note: property is still needed as the `attributeChangedCallback` might be invoked for the first time before the shadow DOM is constructed. Added the test for it creating button dynamically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/125)
> refactor: use attributeChangedCallback for aria-label

- theme/lumo/vaadin-button-styles.html
For default and primary themes, to enable theming inside a notification.
Connects to https://github.com/vaadin/vaadin-notification/issues/104
Related branch for notification, which depends on this feature: https://github.com/vaadin/vaadin-notification/compare/button-color-variables
> Add CSS variables for lumo background and text colors

- bower.json
- gen-tsd.json
- magi-p3-post.js
- package.json
- src/vaadin-button.html
Fixes #145 
Generated file `vaadin-button.d.ts` looks like this:
```ts
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {GestureEventListeners} from '@polymer/polymer/lib/mixins/gesture-event-listeners.js';
import {ThemableMixin} from '@vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js';
import {ControlStateMixin} from '@vaadin/vaadin-control-state-mixin/vaadin-control-state-mixin.js';
import {ElementMixin} from '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
import {addListener} from '@polymer/polymer/lib/utils/gestures.js';
declare class ButtonElement extends
ElementMixin(
ControlStateMixin(
ThemableMixin(
GestureEventListeners(
PolymerElement)))) {
readonly focusElement: Element|null; …
```
> feat: prepare for TS defs generation [skip ci]

- .travis.yml
Avoid running both "push" tests and CRON in the same build (see the most recent [example](https://travis-ci.org/github/vaadin/vaadin-button/builds/679849125)).
> chore: fix running CRON tests in SauceLabs
