.travis.yml, README.md, bower.json, package.json, test/index.html, test/visual/test.js, vaadin-button.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/5)
=> Bump Polymer to RC, use polymer-cli for testing

bower.json, vaadin-button.html
Closes #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/10)
=> Include vaadin-themable-mixin

demo/common.html, demo/index.html, test/vaadin-button_test.html, vaadin-button.html
Fixes #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/9)
=> Adding Aria attributes

package.json, test/performance/config.json
`lighthouse` is finally producing stable results. Hallelujah!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/16)
=> Bump lighthouse plugin, increase threshold to 0.85

bower.json, test/index.html, vaadin-button.html
Connects to https://github.com/vaadin/components-team-tasks/issues/243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/18)
=> Depend on control-state-mixin instead of text-field

demo/styling.html, docs.json, test/vaadin-button_test.html, vaadin-button.html, wct.conf.js
Fixes #4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/17)
=> Add active attribute

test/vaadin-button_test.html, vaadin-button.html
Fixes #24 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/23)
=> Don’t set active when disabled

vaadin-button.html
Connected to https://github.com/vaadin/components-team-tasks/issues/251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/25)
=> Throw error when used with wrong Polymer version

analysis.json, vaadin-button.html
Fixes #33
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/34)
=> Add @mixes Polymer.GestureEventListeners annotation

analysis.json, vaadin-button.html
The same as https://github.com/vaadin/vaadin-text-field/pull/108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/44)
=> Remove Polymer.GestureEventListeners

demo/button-lumo-theme-demos.html, theme/lumo/vaadin-button.html
Fixes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/68)
=> Fix tertiary-inline button theme to be aligned properly

theme/lumo/vaadin-button.html
Fixes #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/83)
=> Remove will-change properties

src/vaadin-button.html, test/vaadin-button_test.html
Fixes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/84)
=> Remove active attribute on blur

src/vaadin-button.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/89)
=> Add usage sample

bower.json, theme/material/vaadin-button-styles.html, theme/material/vaadin-button.html
Connected to https://github.com/vaadin/vaadin-material-styles/issues/49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/90)
=> Adding theme/material

demo/button-basic-demos.html
Fixes #88
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/91)
=> Add a demo with a click listener

bower.json
Fixes #98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/101)
=> Update vaadin-control-state-mixin version

README.md
The same as https://github.com/vaadin/vaadin-element-skeleton/pull/158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/104)
=> Use badgen for npm and bower versions badges

src/vaadin-button.html
Reverts vaadin/vaadin-button#108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/110)
=> Revert "Add tabindex -1 to native button"

src/vaadin-button.html, test/vaadin-button_test.html
Fixes #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-button/122)
=> Set aria-label to native button

src/vaadin-button.html, test/button-in-template.html, test/test-suites.js, test/vaadin-button_test.html
Fixes vaadin/vaadin-button-flow#120
=> Fix content change timing issue on Shady DOM
